float64 x_prep
float64 y_prep
float64 z_prep
float64 qx_prep
float64 qy_prep
float64 qz_prep
float64 qw_prep
float64 x_grasp
float64 y_grasp
float64 z_grasp
float64 qx_grasp
float64 qy_grasp
float64 qz_grasp
float64 qw_grasp

---
bool success
