float64 x_prep
float64 y_prep
float64 z_prep
float64 qx_prep
float64 qy_prep
float64 qz_prep
float64 qw_prep
float64 x_place
float64 y_place
float64 z_place
float64 qx_place
float64 qy_place
float64 qz_place
float64 qw_place

---
bool success
